pub mod handlers;
pub mod router;
pub mod wg;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct Agent {
    pub id: Uuid,
    pub name: String,
    pub wg_pubkey: String,
    pub wg_ip: String,
    pub wg_endpoint: Option<String>,
    pub api_port: i32,
    pub status: String,
    pub version: Option<String>,
    pub last_heartbeat: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Deserialize)]
pub struct RegisterAgentRequest {
    /// UUID v7 generated by the agent install script
    pub agent_id: Uuid,
    pub name: String,
    /// Agent's WireGuard public key (base64)
    pub wg_pubkey: String,
    /// Agent VPS public IP (for WG endpoint display)
    pub wg_endpoint: Option<String>,
    pub api_port: Option<i32>,
}

#[derive(Debug, Serialize)]
pub struct AgentSummary {
    pub id: Uuid,
    pub name: String,
    pub status: String,
    pub wg_ip: String,
    pub version: Option<String>,
    pub last_heartbeat: Option<DateTime<Utc>>,
}
