name: release-agent-test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing softprops"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          tag_name: ${{ inputs.tag != '' && inputs.tag || github.ref_name }}
          generate_release_notes: true
