name: release-agent-test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            rust-target: x86_64-unknown-linux-musl
            use_cross: false
          - arch: arm64
            rust-target: aarch64-unknown-linux-musl
            use_cross: true
    steps:
      - run: echo "arch=${{ matrix.arch }} use_cross=${{ matrix.use_cross }}"
